<main class="container">
    <section id="customerRegister">
        <article>
            <h2>Déjà client</h2>
            <?php if ($errorMessage):?>
                <div class="error"><?=$errorMessage?></div>
            <?php endif;?>
            <form action="<?= $requestUrl ?>/customer/" method="post">
                <div>
                    <label for="email">Email :</label>
                    <input type="email" id="email" name="email" value="<?=$email?>">
                </div>
                <div>
                    <label for="password">Mot de passe :</label>
                    <input type="password" value="" name="password" id="password">
                </div>
                <input type="submit" value="Connexion" class="btn" >
            </form>
        </article>
        <article>
            <h2>Nouveau client</h2>
            <a class="btn" href="<?= $requestUrl ?>/customer/create/">Créer votre compte</a>
        </article>
    </section>
</main>