<main class="container">
    <section id="product">
        <section id="product-detail">
            <div id="product-name">
                <h1><?=$product['prod_name']?></h1>
                <h2><?=$product['prod_subtitle']?></h2>
                <p>Ref : 133742</p>
            </div>
            <div id="rating">
                <i class="gold fa fa-star" aria-hidden="true"></i>
                <i class="gold fa fa-star" aria-hidden="true"></i>
                <i class="gold fa fa-star" aria-hidden="true"></i>
                <i class="gold fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <a href="#">Voir les 56 avis clients</a>
            </div>
        </section>
        <section id="product-quantity">
            <?php if(!is_null($product['prod_picture'])):?>
                <img src="<?= $wwwUrl ?>/uploads/products/<?=$product['prod_picture']?>" alt="<?=$product['prod_name']?>" />
            <?php else:?>
                <img src="https://via.placeholder.com/300" />
            <?php endif;?>
            <div class="price">
                <?php if($variations):?>
                    <select name="variation" id="variation">
                        <?php foreach($variations as $variation):?>
                            <option value="<?=$variation['prodv_id']?>" data-price="<?=$variation['priceTTC']?>"><?=$variation['prodv_name'].' ('.$variation['priceTTC'].' €)'?></option>
                        <?php endforeach;?>
                    </select>
                    <h3>
                        <?php foreach($variations as $index=>$variation):?>
                            <span id="variation<?=$variation['prodv_id']?>"><?=$variation['priceTTC'];?> €</span>
                        <?php endforeach;?>
                    </h3>
                <?php else:?>
                    <h3><?=$product['priceTTC'];?> €</h3>
                <?php endif?>
                <p><label for="quantity">Quantité :</label> <input type="number" id="quantity" name="quantity" value="1" min="1" max="20" /></p>
                <a class="btn" href="#">Ajouter au panier</a>
                <a id="wishlist" href="#">Ajouter à ma liste d'envie</a>
            </div>
        </section>
        <section id="product-description">
            <?=$product['prod_description']?>
        </section>
    </section>
</main>

<script>
/** Un petit coup de JS pour changer le prix en fonction de la variation */
$(function(){
    $('h3 span').each(function() {
        if(this.id != 'variation'+$('#variation').val())
            $(this).toggle();
    });

    $('#variation').on('change',function(){
        $('h3 span').hide();
        $('#variation'+$(this).val()).show();
    });
});
</script>