<h3>Les dernières commandes</h3>
<section class="table-responsive"> 
    <table class="tableDonnee table">
        <thead>
            <th>Id</th>
            <th>Date</th>
            <th>Client</th>
            <th>Montant HT</th>
            <th>Montant TTC</th>
            <th></th>
        </thead>
        <tbody>
            <?php// foreach($categories as $categorie):?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><a href="<?= $requestUrl ?>/admin/orders/view/?id="><i class="fas fa-eye"></i></a></td>
                </tr>
            <?php //endforeach;?>
        </tbody>
    </table>
</section>

<h3>Les derniers clients</h3>
<section class="table-responsive"> 
    <table  class="tableDonnee table">
        <thead>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Date d'inscription</th>
            <th>Email</th>
            <th></th>
        </thead>
        <tbody>
            <?php// foreach($categories as $categorie):?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><a href="<?= $requestUrl ?>/admin/orders/view/?id="><i class="fas fa-eye"></i></a></td>
                </tr>
            <?php //endforeach;?>
        </tbody>
    </table>
</section>